language: cpp
compiler:
  - gcc
  - clang
before_install:
  - git submodule update --init
  - yes | sudo add-apt-repository ppa:mapnik/boost
  - yes | sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - apt-file search alternatives
install: sudo apt-get install libicu-dev boost1.49 libboost-chrono1.49-dev libboost-filesystem1.49-dev libboost-program-options1.49-dev libboost-system1.49-dev libboost-thread1.49-dev gcc-4.8 g++-4.8
script: $CXX --version && autoreconf -i && ./configure && make -j2 check
