language: cpp
compiler:
  - gcc
  - clang
before_install:
  - git submodule update --init
  - sudo echo "deb http://ppa.launchpad.net/mapnik/boost/ubuntu precise main" >> /etc/apt/sources.list
  - sudo echo "deb-src http://ppa.launchpad.net/mapnik/boost/ubuntu precise main" >> /etc/apt/sources.list
  - sudo apt-get update
install: sudo apt-get install libicu-dev boost1.49
script: make
