language: cpp
compiler:
  - gcc
  - clang
before_install:
  - git submodule update --init
  - yes | sudo add-apt-repository ppa:mapnik/boost
  - sudo apt-get update
install: sudo apt-get install libicu-dev boost1.49
script: make
