language: cpp
compiler:
  - gcc
  - clang
before_install:
  - git submodule update --init
  - yes | sudo add-apt-repository ppa:mapnik/boost
  - sudo apt-get update
install: sudo apt-get install libicu-dev boost1.49 libboost-chrono1.49-dev libboost-filesystem1.49-dev libboost-program-options1.49-dev libboost-system1.49-dev libboost-thread1.49-dev
script: cat "/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/bits/unique_ptr.h" && autoreconf -i && ./configure && make -j2 check
